pipeline {
    agent any
    environment {
        IMAGE_NAME = 'andreigur5001/registry'
        VERSION = "v${env.BUILD_NUMBER}"
        REPO = 'andreigur5001/registry'
        CREDENTIALS_ID = '64f101d3-a483-4bf1-bcf6-185951e55836'
        SNYK_TOKEN = credentials('01e4bae7-36f8-4409-8518-4985944d0152')
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${VERSION}-build", "-f welcome/Dockerfile .")
                }
            }
        }
        stage('Lint') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${VERSION}-lint", "--target lint -f welcome/Dockerfile .")
                    catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                        sh "docker run --rm ${IMAGE_NAME}:${VERSION}-lint"
                    }
                }
            }
        }
        stage('Snyk') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${VERSION}-snyk", "--target build -f welcome/Dockerfile .")
                    withEnv(["SNYK_TOKEN=${env.SNYK_TOKEN}"]) {
                        sh "docker run --rm -e SNYK_TOKEN=${env.SNYK_TOKEN} ${IMAGE_NAME}:${VERSION}-snyk snyk test --docker ${IMAGE_NAME}:${VERSION}-snyk"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${VERSION}-test", "--target test -f welcome/Dockerfile .")
                    sh "docker run --rm ${IMAGE_NAME}:${VERSION}-test"
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', CREDENTIALS_ID) {
                        docker.image("${IMAGE_NAME}:${VERSION}-build").push("${VERSION}-build")
                        docker.image("${IMAGE_NAME}:${VERSION}-lint").push("${VERSION}-lint")
                        docker.image("${IMAGE_NAME}:${VERSION}-test").push("${VERSION}-test")
                    }
                }
            }
        }
    }
}
